- name: include vars
  include_vars: "vars_elasticsearch.yml"

# 上传配置文件
- name: copy configuration file
  template:
    src: "/ansible-playbook/elasticsearch/config/elasticsearch.yml.j2"
    dest: "{{ es_home_dir }}/{{ es_tar_unzip_dir }}/config/elasticsearch.yml"
  check_mode: no
- name: copy jvm file
  template:
    src: "/ansible-playbook/elasticsearch/config/jvm.options.j2"
    dest: "{{ es_home_dir }}/{{ es_tar_unzip_dir }}/config/jvm.options"
  check_mode: no
- name: copy gc options
  template:
    src: "/ansible-playbook/elasticsearch/config/jvm.options.d/gc.options.j2"
    dest: "{{ es_home_dir }}/{{ es_tar_unzip_dir }}/config/jvm.options.d/gc.options"
  check_mode: no
