- name: include vars
  include_vars: "vars_elasticsearch.yml"

- name: create the keystore if it doesn't exist yet
  become: yes
  command: >
   {{ es_home }}/bin/elasticsearch-keystore create
  args:
    creates: "{{ es_home }}/config/elasticsearch.keystore"
  environment:
    ES_PATH_CONF: "{{ es_home }}/config"

- name: Check if bootstrap password is set
  become: yes
  command: >
   {{ es_home }}/bin/elasticsearch-keystore list
  register: list_keystore
  changed_when: False
  environment:
    ES_PATH_CONF: "{{ es_home }}/config"
  check_mode: no

- name: Create Bootstrap password for elastic user
  become: yes
  shell: echo {{ es_api_basic_auth_password | quote }} | {{ es_home }}/bin/elasticsearch-keystore add -x 'bootstrap.password'
  when:
    - es_api_basic_auth_username is defined and list_keystore is defined and es_api_basic_auth_username == 'elastic' and 'bootstrap.password' not in list_keystore.stdout_lines
  environment:
    ES_PATH_CONF: "{{ es_home }}/config"
  no_log: false
  check_mode: no

- name: Set elasticsearch.keystore Permissions
  become: yes
  file:
    state: file
    path: "{{ es_home }}/config/elasticsearch.keystore"
    owner: root
    group: "{{ es_group }}"
    mode: "0660"
  check_mode: no
