- name: copy configuration file
  copy:
    src: "/ansible-playbook/elasticsearch/config/elasticsearch.yml"
    dest: "{{ es_home_dir }}/elasticsearch-7.8.1/config"
  check_mode: no
- name: copy jvm file
  copy:
    src: "/ansible-playbook/elasticsearch/config/jvm.options"
    dest: "{{ es_home_dir }}/elasticsearch-7.8.1/config"
  check_mode: no
- name: copy gc options
  copy:
    src: "/ansible-playbook/elasticsearch/config/jvm.options.d/gc.options"
    dest: "{{ es_home_dir }}/elasticsearch-7.8.1/config/jvm.options.d/gc.options"
  check_mode: no
- name: copy log4j file
  copy:
    src: "/ansible-playbook/elasticsearch/config/log4j2.properties"
    dest: "{{ es_home_dir }}/elasticsearch-7.8.1/config"
  check_mode: no
