# Install MySQL Router Nodes

- hosts: 10.1.207.180
  user: mysql
  become: no
  become_user: root
  become_method: su
  tasks:
    - include_tasks: task_mysql_router_init.yml

- hosts: 10.1.207.181
  user: mysql
  become: no
  become_user: root
  become_method: su
  tasks:
    - include_tasks: task_mysql_router_init.yml

- hosts: 10.1.207.182
  user: mysql
  become: no
  become_user: root
  become_method: su
  tasks:
    - include_tasks: task_mysql_router_init.yml
