- name: include vars
  include_vars: "vars_mysql.yml"

# 初始化目录
- name: create others directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ mysql_user }}"
    group: "{{ mysql_group }}"
    mode: "2750"
  with_items:
    - "{{ mysql_run_dir }}"
    - "{{ mysql_log_dir }}"
    - "{{ mysql_data_dir }}"
    - "{{ mysql_dump_dir }}"
    - "{{ mysql_script_dir }}"
    - "{{ mysql_fast_data_dir }}"
    - "{{ mysql_fast_binlog_dir }}"
    - "{{ mysql_fast_relaylog_dir }}"
  check_mode: no
  become: yes

# 上传 my.cnf 到 ~/.my.cnf
- name: copy my.cnf to ~/.my.cnf
  template:
    src: "/ansible-playbook/mysql/config/my.cnf.j2"
    dest: "$HOME/.my.cnf"
  check_mode: no

# 设置 mysql.server 脚本中的 basedir
- name: configuring mysql.server basedir variables
  lineinfile:
    dest: "{{ mysql_home_dir }}/{{ mysql_tar_unzip_dir }}/support-files/mysql.server"
    regexp: '^basedir=.*$'
    line: 'basedir={{ mysql_home_dir }}/{{ mysql_tar_unzip_dir }}'
    backrefs: yes
    state: present
  check_mode: no

# 设置 mysql.server 脚本中的 datadir
- name: configuring mysql.server datadir variables
  lineinfile:
    dest: "{{ mysql_home_dir }}/{{ mysql_tar_unzip_dir }}/support-files/mysql.server"
    regexp: '^datadir=.*$'
    line: 'datadir={{ mysql_data_dir }}'
    backrefs: yes
    state: present
  check_mode: no

# copy mysql.server to ~/mysql.server
- name: copy mysql.server to ~/mysql.server
  shell: "cp {{ mysql_home_dir }}/{{ mysql_tar_unzip_dir }}/support-files/mysql.server ~/mysql.server"
  check_mode: no

# 移除 /etc/my.cnf
- name: check /etc/my.cnf
  stat: path=/etc/my.cnf
  register: check_etc_my_cnf
  check_mode: no
- name: remove /etc/my.cnf
  command: mv /etc/my.cnf /etc/my.cnf.deleted
  check_mode: no
  become: yes
  when: check_etc_my_cnf.stat.exists

# 移除 /etc/mysql/my.cnf
- name: check /etc/mysql/my.cnf
  stat: path=/etc/mysql/my.cnf
  register: check_etc_mysql_my_cnf
  check_mode: no
- name: remove /etc/mysql/my.cnf
  command: mv /etc/mysql/my.cnf /etc/mysql/my.cnf.deleted
  check_mode: no
  become: yes
  when: check_etc_mysql_my_cnf.stat.exists

# 上传卸载脚本 mysql_uninstall.sh 到 etc 目录
- name: copy mysql_uninstall.sh
  template:
    src: "/ansible-playbook/mysql/config/mysql_uninstall.sh.j2"
    dest: "$HOME/mysql_uninstall.sh"
    mode: u=rwx,g=rx,o=rx
  check_mode: no
  become: yes

# 设置 MYSQL_HOME 环境变量
- name: configuring MYSQL_HOME variables
  lineinfile:
    dest: ~/.bash_profile
    regexp: '^export MYSQL_HOME.*'
    line: "\n#ansible-playbook\nexport MYSQL_HOME={{ mysql_home_dir }}/{{ mysql_tar_unzip_dir }}"
    state: present
  check_mode: no

# 设置 MYSQLSH_HOME 环境变量
- name: configuring MYSQLSH_HOME variables
  lineinfile:
    dest: ~/.bash_profile
    regexp: '^export MYSQLSH_HOME.*'
    line: "export MYSQLSH_HOME={{ mysql_home_dir }}/{{ mysql_shell_tar_unzip_dir }}"
    state: present
  check_mode: no

# 设置 MYSQL_HOME 和 MYSQLSH_HOME 到 PATH
- name: configuring PATH variables
  lineinfile:
    dest: ~/.bash_profile
    regexp: '^PATH=.*MYSQL_HOME'
    insertafter: 'EOF'
    line: "PATH=$PATH:${MYSQL_HOME}/bin:${MYSQLSH_HOME}/bin\nexport PATH"
    state: present
  check_mode: no
