- name: include vars
  include_vars: "vars_mysql.yml"

# 初始化目录
- name: create others directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ mysql_user }}"
    group: "{{ mysql_group }}"
    mode: "2750"
  with_items:
    - "{{ mysql_run_dir }}"
    - "{{ mysql_log_dir }}"
    - "{{ mysql_data_dir }}"
    - "{{ mysql_dump_dir }}"
    - "{{ mysql_fast_data_dir }}"
    - "{{ mysql_fast_binlog_dir }}"
    - "{{ mysql_fast_relaylog_dir }}"
  check_mode: no

- name: copy my.cnf
  template:
    src: "/ansible-playbook/mysql/config/my.cnf.j2"
    dest: "{{ mysql_home_dir }}/my.cnf"
  check_mode: no

# 上传启动文件
- name: copy my.sh file
  template:
    src: "/ansible-playbook/mysql/bin/my.sh.j2"
    dest: "{{ mysql_home_dir }}/my.sh"
    mode: 0755
  check_mode: no
  
# 设置 MYSQL_HOME 环境变量

# 设置 MYSQLSH_HOME 环境变量

# 设置 MYSQL_HOME 和 MYSQLSH_HOME 到 PATH
