- name: include vars
  include_vars: "vars_mysql.yml"

# 初始化目录
- name: create others directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ mysql_user }}"
    group: "{{ mysql_group }}"
    mode: "2750"
  with_items:
    - "{{ mysql_run_dir }}"
    - "{{ mysql_log_dir }}"
    - "{{ mysql_data_dir }}"
    - "{{ mysql_dump_dir }}"
    - "{{ mysql_script_dir }}"
    - "{{ mysql_fast_data_dir }}"
    - "{{ mysql_fast_binlog_dir }}"
    - "{{ mysql_fast_relaylog_dir }}"
  check_mode: no
  become: yes

# 上传 my.conf 到 etc 目录
- name: copy my.cnf to etc
  template:
    src: "/ansible-playbook/mysql/config/my.cnf.j2"
    dest: "/etc/my.cnf"
  check_mode: no
  become: yes

# 设置 MYSQL_HOME 环境变量
- name: configuring MYSQL_HOME variables
  lineinfile:
    dest: ~/.bash_profile
    regexp: '^export MYSQL_HOME.*'
    line: "\n#ansible-playbook\nexport MYSQL_HOME={{ mysql_home_dir }}/{{ mysql_tar_unzip_dir }}"
    state: present
  check_mode: no

# 设置 MYSQLSH_HOME 环境变量
- name: configuring MYSQLSH_HOME variables
  lineinfile:
    dest: ~/.bash_profile
    regexp: '^export MYSQLSH_HOME.*'
    line: "export MYSQLSH_HOME={{ mysql_home_dir }}/{{ mysql_shell_tar_unzip_dir }}"
    state: present
  check_mode: no

# 设置 MYSQL_HOME 和 MYSQLSH_HOME 到 PATH
- name: configuring PATH variables
  lineinfile:
    dest: ~/.bash_profile
    regexp: '^PATH=.*MYSQL_HOME'
    insertafter: 'EOF'
    line: "PATH=$PATH:${MYSQL_HOME}/bin:${MYSQLSH_HOME}/bin\nexport PATH"
    state: present
  check_mode: no
