- name: include vars
  include_vars: "vars_antdb.yml"

# 设置 ADB_HOME 环境变量
- name: configuring environment ADB_HOME
  lineinfile:
    dest: ~/.bashrc
    regexp: '^export ADB_HOME=.*$'
    line: "export ADB_HOME={{ antdb_app_dir }}"
    state: present
  check_mode: no

# 设置 ADB_HOME 到 PATH
- name: configuring environment LD_LIBRARY_PATH
  lineinfile:
    dest: ~/.bashrc
    regexp: '^export LD_LIBRARY_PATH=.*$'
    line: "export LD_LIBRARY_PATH=${ADB_HOME}/lib:$LD_LIBRARY_PATH"
    state: present
  check_mode: no

# Configuring environment mgrdata
- name: configuring environment mgrdata
  lineinfile:
    dest: ~/.bashrc
    regexp: '^export mgrdata=.*'
    insertafter: 'EOF'
    line: "export mgrdata={{ antdb_mgr_dir }}"
    state: present
  check_mode: no

# Configuring alias adbmgr
- name: configuring alias adbmgr
  lineinfile:
    dest: ~/.bashrc
    regexp: '^alias adbmgr=.*'
    line: "alias adbmgr='psql -p 16432 -d postgres'"
    state: present
  check_mode: no

# Configuring alias mgr_stop
- name: configuring alias mgr_stop
  lineinfile:
    dest: ~/.bashrc
    regexp: '^alias mgr_stop=.*'
    line: "alias mgr_stop='mgr_ctl stop -D $mgrdata -m fast'"
    state: present
  check_mode: no

# Configuring alias mgr_start
- name: configuring alias mgr_start
  lineinfile:
    dest: ~/.bashrc
    regexp: '^alias mgr_start=.*'
    line: "alias mgr_start='mgr_ctl start -D $mgrdata'"
    state: present
  check_mode: no

# 设置 ADB_HOME 到 PATH
- name: configuring environment PATH
  lineinfile:
    dest: ~/.bashrc
    regexp: '^export PATH=.*'
    line: "export PATH=${ADB_HOME}/bin:$PATH"
    state: present
  check_mode: no
