- hosts: 10.1.207.177
  user: kafka
  become: no
  become_user: root
  become_method: su
  tasks:
    - include_tasks: task_kafka_pre_checks.yml
    - include_tasks: task_kafka_os.yml
    - include_tasks: task_kafka_upload.yml
    - include_tasks: task_zookeeper_config.yml
    - include_tasks: task_kafka_config.yml

- hosts: 10.1.207.178
  user: kafka
  become: no
  become_user: root
  become_method: su
  tasks:
    - include_tasks: task_kafka_pre_checks.yml
    - include_tasks: task_kafka_os.yml
    - include_tasks: task_kafka_upload.yml
    - include_tasks: task_zookeeper_config.yml
    - include_tasks: task_kafka_config.yml

- hosts: 10.1.207.183
  user: kafka
  become: no
  become_user: root
  become_method: su
  tasks:
    - include_tasks: task_kafka_pre_checks.yml
    - include_tasks: task_kafka_os.yml
    - include_tasks: task_kafka_upload.yml
    - include_tasks: task_zookeeper_config.yml
    - include_tasks: task_kafka_config.yml
