- hosts: 10.1.207.177
  user: kafka
  become: no
  become_user: root
  become_method: su
  tasks:
    - include_tasks: task_kafka_start.yml

- hosts: 10.1.207.178
  user: kafka
  become: no
  become_user: root
  become_method: su
  tasks:
    - include_tasks: task_kafka_start.yml

- hosts: 10.1.207.183
  user: kafka
  become: no
  become_user: root
  become_method: su
  tasks:
    - include_tasks: task_kafka_start.yml
