# Configure iotdb-cluster.properties
- name: include vars
  include_vars: "vars_iotdb.yml"

- name: copy iotdb-cluster.properties template
  copy:
    src: "{{ iotdb_home_dir }}/{{ iotdb_tar_unzip_dir }}/conf/iotdb-cluster.properties"
    dest: "{{ iotdb_conf_dir }}/iotdb-cluster.properties"
    remote_src: yes
  check_mode: no

- name: iotdb-cluster cluster_name
  lineinfile:
    dest: "{{ iotdb_conf_dir }}/iotdb-cluster.properties"
    regexp: "^# cluster_name=.*"
    line: "cluster_name={{ iotdb.cluster.cluster_name }}"
    state: present
  check_mode: no

- name: iotdb-cluster internal_ip
  lineinfile:
    dest: "{{ iotdb_conf_dir }}/iotdb-cluster.properties"
    regexp: "^internal_ip=.*"
    line: "internal_ip={{ inventory_hostname }}"
    state: present
  check_mode: no

- name: iotdb-cluster internal_meta_port
  lineinfile:
    dest: "{{ iotdb_conf_dir }}/iotdb-cluster.properties"
    regexp: "^internal_meta_port=.*"
    line: "internal_meta_port={{ iotdb.cluster.internal_meta_port }}"
    state: present
  check_mode: no

- name: iotdb-cluster internal_data_port
  lineinfile:
    dest: "{{ iotdb_conf_dir }}/iotdb-cluster.properties"
    regexp: "^internal_data_port=.*"
    line: "internal_data_port={{ iotdb.cluster.internal_data_port }}"
    state: present
  check_mode: no

- name: iotdb-cluster seed_nodes
  lineinfile:
    dest: "{{ iotdb_conf_dir }}/iotdb-cluster.properties"
    regexp: "seed_nodes=.*"
    line: "seed_nodes={{ iotdb.cluster.seed_nodes }}"
    state: present
  check_mode: no

- name: iotdb-cluster default_replica_num
  lineinfile:
    dest: "{{ iotdb_conf_dir }}/iotdb-cluster.properties"
    regexp: "^default_replica_num=.*"
    line: "default_replica_num={{ iotdb.cluster.default_replica_num }}"
    state: present
  check_mode: no

- name: iotdb-cluster consistency_level
  lineinfile:
    dest: "{{ iotdb_conf_dir }}/iotdb-cluster.properties"
    regexp: "^# consistency_level=.*"
    line: "consistency_level={{ iotdb.cluster.consistency_level }}"
    state: present
  check_mode: no

- name: iotdb-cluster cluster_info_public_port
  lineinfile:
    dest: "{{ iotdb_conf_dir }}/iotdb-cluster.properties"
    regexp: "^#cluster_info_public_port=.*"
    line: "cluster_info_public_port={{ iotdb.cluster.cluster_info_public_port }}"
    state: present
  check_mode: no

- name: iotdb-cluster is_enable_raft_log_persistence
  lineinfile:
    dest: "{{ iotdb_conf_dir }}/iotdb-cluster.properties"
    regexp: "^# is_enable_raft_log_persistence=.*"
    line: "is_enable_raft_log_persistence={{ iotdb.cluster.is_enable_raft_log_persistence }}"
    state: present
  check_mode: no
