- hosts: 10.1.207.180
  user: redis
  become: no
  become_user: root
  become_method: su
  tasks:
    - include_tasks: task_sentinel_start.yml

- hosts: 10.1.207.181
  user: redis
  become: no
  become_user: root
  become_method: su
  vars:
  tasks:
    - include_tasks: task_sentinel_start.yml

- hosts: 10.1.207.182
  user: redis
  become: no
  become_user: root
  become_method: su
  vars:
  tasks:
    - include_tasks: task_sentinel_start.yml
