- hosts: 10.1.207.180
  user: redis
  become: no
  become_user: root
  become_method: su
  vars:
    im_master: true
  tasks:
    - include_tasks: task_redis_os.yml
    - include_tasks: task_redis_upload.yml
    - include_tasks: task_redis_install.yml
    - include_tasks: task_redis_config.yml

- hosts: 10.1.207.181
  user: redis
  become: no
  become_user: root
  become_method: su
  vars:
  tasks:
    - include_tasks: task_redis_os.yml
    - include_tasks: task_redis_upload.yml
    - include_tasks: task_redis_install.yml
    - include_tasks: task_redis_config.yml

- hosts: 10.1.207.182
  user: redis
  become: no
  become_user: root
  become_method: su
  vars:
  tasks:
    - include_tasks: task_redis_os.yml
    - include_tasks: task_redis_upload.yml
    - include_tasks: task_redis_install.yml
    - include_tasks: task_redis_config.yml
