- name: include vars
  include_vars: "vars_redis.yml"

# 上传配置文件
- name: copy redis configuration file
  template:
    src: "/ansible-playbook/redis/config/redis.conf.j2"
    dest: "{{ redis_conf_dir }}/redis.conf"
  check_mode: no

# 上传配置文件
- name: copy sentinel configuration file
  template:
    src: "/ansible-playbook/redis/config/sentinel.conf.j2"
    dest: "{{ redis_conf_dir }}/sentinel.conf"
  check_mode: no

- name: Delete Tar ball
  shell: "rm -rf {{ redis_home_dir }}/*"

- name: Install Succeed
  debug:
    msg: Install Succeed!
  check_mode: no
